create table if not exists public.color_presets (
  id integer generated by default as identity primary key,
  name varchar(120) not null unique,
  brightness double precision not null default 1.0,
  contrast double precision not null default 1.0,
  saturation double precision not null default 1.0,
  sharpness double precision not null default 1.0,
  temperature double precision not null default 0.0,
  auto_white_balance boolean not null default true,
  shadow_reduction double precision not null default 0.0,
  face_enhancement double precision not null default 0.0,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

create index if not exists ix_color_presets_id on public.color_presets (id);
create unique index if not exists ix_color_presets_name on public.color_presets (name);

create table if not exists public.photo_templates (
  id integer generated by default as identity primary key,
  name varchar(140) not null,
  description text,
  width integer not null,
  height integer not null,
  shape varchar(40) not null default 'rectangular',
  background_color varchar(40) not null default '#ffffff',
  transparent_background boolean not null default false,
  border_radius integer not null default 0,
  output_format varchar(10) not null default 'PNG',
  output_quality integer not null default 92,
  color_preset_id integer references public.color_presets(id),
  face_expand_x double precision not null default 2.2,
  face_expand_y double precision not null default 2.8,
  face_offset_y double precision not null default -0.15,
  zoom_default double precision not null default 1.0,
  offset_x_default double precision not null default 0.0,
  offset_y_default double precision not null default 0.0,
  head_top_margin double precision not null default 0.12,
  shoulder_visibility double precision not null default 0.25,
  crop_mode varchar(40) not null default 'head_shoulders',
  status varchar(20) not null default 'active',
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

create index if not exists ix_photo_templates_id on public.photo_templates (id);
create index if not exists ix_photo_templates_name on public.photo_templates (name);

create table if not exists public.photo_jobs (
  id integer generated by default as identity primary key,
  template_id integer not null references public.photo_templates(id),
  type varchar(20) not null default 'batch',
  status varchar(30) not null default 'created',
  total_items integer not null default 0,
  processed_items integer not null default 0,
  failed_items integer not null default 0,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

create index if not exists ix_photo_jobs_id on public.photo_jobs (id);

create table if not exists public.photo_job_items (
  id integer generated by default as identity primary key,
  job_id integer not null references public.photo_jobs(id) on delete cascade,
  original_filename varchar(255) not null,
  original_photo_path varchar(500) not null,
  processed_photo_path varchar(500),
  debug_face_path varchar(500),
  debug_crop_path varchar(500),
  face_detected boolean not null default false,
  face_count integer not null default 0,
  confidence double precision,
  manual_adjusted boolean not null default false,
  status varchar(30) not null default 'uploaded',
  error_message text,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

create index if not exists ix_photo_job_items_id on public.photo_job_items (id);
